name: Update fork
on:
  workflow_dispatch:
  schedule:
    # actually, ~5 minutes is the highest
    # effective frequency you will get
    - cron:  '5 * * * *'
jobs:
  update_my_showdown_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Get the output time  # test
        run: echo "Running the 'Update fork' workflow"
      - name: Update fork
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          upstream_repository: smogon/pokemon-showdown
          target_repository: szymonWojdat/pokemon-showdown
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
