# .github/workflows/example.yml

name: Update fork
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '30 * * * *'
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: smogon/pokemon-showdown
          target_repository: szymonWojdat/pokemon-showdown
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
